# Generated by Django 5.2.4 on 2025-09-30 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitationtoken',
            name='phone',
            field=models.CharField(default='+1234567890', help_text='Phone number is required for SMS invitations', max_length=30),
            preserve_default=False,
        ),
    ]
