# Generated by Django 5.2.4 on 2025-09-30 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_make_phone_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(default='+000000000', help_text='Phone number for contact and SMS notifications', max_length=30),
            preserve_default=False,
        ),
    ]
