# Generated by Django 5.2.4 on 2025-11-04 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, default='', help_text='Phone number for contact and SMS notifications', max_length=30),
        ),
    ]
