# Generated by Django 5.2.4 on 2025-10-01 16:17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_add_sales_reports'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Human-readable name for the material', max_length=255)),
                ('category', models.CharField(choices=[('paper', 'Paper'), ('ink', 'Ink'), ('binding', 'Binding Supplies'), ('other', 'Other')], default='other', max_length=50)),
                ('unit', models.CharField(help_text='Unit of measure (reams, liters, sheets, etc.)', max_length=50)),
                ('current_stock', models.DecimalField(decimal_places=4, default=0, help_text='Current stock quantity', max_digits=12)),
                ('reorder_level', models.DecimalField(decimal_places=4, default=0, help_text='Minimum stock level before reorder alert', max_digits=12)),
                ('archived', models.BooleanField(default=False, help_text='Soft delete flag')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='JobMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_used', models.DecimalField(decimal_places=4, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_materials_recorded', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_materials', to='services.work')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_usages', to='services.material')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Procurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(max_length=255)),
                ('supplier_contact', models.CharField(blank=True, max_length=255, null=True)),
                ('supplier_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('supplier_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('quantity_ordered', models.DecimalField(decimal_places=4, max_digits=12)),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('order_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('delivery_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procurements_created', to=settings.AUTH_USER_MODEL)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procurements', to='services.material')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('inflow', 'Inflow'), ('outflow', 'Outflow')], max_length=10)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=12)),
                ('reference_type', models.CharField(choices=[('procurement', 'Procurement'), ('job', 'Job Usage'), ('adjustment', 'Manual Adjustment')], max_length=20)),
                ('reference_id', models.PositiveIntegerField(help_text='ID of procurement, job, or adjustment record')),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='services.material')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
