# Generated by Django 5.2.4 on 2025-10-04 15:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_add_procurement_inventory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='reference_id',
            field=models.PositiveIntegerField(help_text='ID of procurement, job, adjustment, or material usage record'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='reference_type',
            field=models.CharField(choices=[('procurement', 'Procurement'), ('job', 'Job Usage'), ('adjustment', 'Manual Adjustment'), ('material_usage', 'Material Pickup')], max_length=20),
        ),
        migrations.CreateModel(
            name='MaterialUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_taken', models.DecimalField(decimal_places=4, max_digits=12)),
                ('taken_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(blank=True, help_text='Optional note about the material usage', null=True)),
                ('stock_before', models.DecimalField(decimal_places=4, help_text='Stock level before taking materials', max_digits=12)),
                ('stock_after', models.DecimalField(decimal_places=4, help_text='Stock level after taking materials', max_digits=12)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_records', to='services.material')),
                ('taken_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials_taken', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-taken_at'],
            },
        ),
    ]
