# Generated by Django 5.2.4 on 2025-11-03 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_alter_stockmovement_reference_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='works', to='services.customer'),
        ),
    ]
