# Generated by Django 5.2.4 on 2025-11-03 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_make_work_customer_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcategory',
            name='send_completion_notification',
            field=models.BooleanField(default=False, help_text='Send SMS notification to customer when work in this category is completed'),
        ),
    ]
