# Generated by Django 5.2.4 on 2025-11-03 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_add_notification_to_job_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='customer',
        ),
        migrations.AddField(
            model_name='work',
            name='customer_name',
            field=models.CharField(default='Unknown Customer', help_text='Customer name', max_length=255),
        ),
        migrations.AddField(
            model_name='work',
            name='customer_phone',
            field=models.CharField(default='N/A', help_text='Customer phone number for SMS notifications', max_length=20),
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
