# Generated by Django 5.2.4 on 2025-11-04 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_remove_customer_model_add_fields_to_work'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobmaterial',
            name='quantity_used',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='material',
            name='current_stock',
            field=models.IntegerField(default=0, help_text='Current stock quantity'),
        ),
        migrations.AlterField(
            model_name='material',
            name='reorder_level',
            field=models.IntegerField(default=0, help_text='Minimum stock level before reorder alert'),
        ),
        migrations.AlterField(
            model_name='materialusage',
            name='quantity_taken',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='materialusage',
            name='stock_after',
            field=models.IntegerField(help_text='Stock level after taking materials'),
        ),
        migrations.AlterField(
            model_name='materialusage',
            name='stock_before',
            field=models.IntegerField(help_text='Stock level before taking materials'),
        ),
        migrations.AlterField(
            model_name='procurement',
            name='quantity_ordered',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
