# Generated by Django 5.2.4 on 2025-11-04 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_alter_jobmaterial_quantity_used_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='procurement',
            name='supplier_contact',
        ),
        migrations.RemoveField(
            model_name='procurement',
            name='supplier_email',
        ),
        migrations.RemoveField(
            model_name='procurement',
            name='supplier_name',
        ),
        migrations.RemoveField(
            model_name='procurement',
            name='supplier_phone',
        ),
    ]
