# Generated by Django 5.2.4 on 2025-11-05 13:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0011_remove_procurement_supplier_contact_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyexpense',
            name='recorded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses_recorded', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dailysalesreport',
            name='generated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_reports_generated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='materialusage',
            name='taken_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materials_taken', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='salesreportnote',
            name='added_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_notes_added', to=settings.AUTH_USER_MODEL),
        ),
    ]
