# Generated by Django 5.2.4 on 2025-11-10 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0012_preserve_work_on_staff_deletion'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Customer full name', max_length=255)),
                ('phone', models.CharField(help_text='Customer phone number (unique)', max_length=20, unique=True)),
                ('opted_out', models.BooleanField(default=False, help_text='Customer has opted out of promotional messages')),
                ('first_work_date', models.DateTimeField(auto_now_add=True, help_text='Date when customer was first added')),
                ('last_work_date', models.DateTimeField(auto_now=True, help_text='Date of most recent work')),
                ('total_works', models.IntegerField(default=1, help_text='Total number of works for this customer')),
                ('total_spent', models.DecimalField(decimal_places=2, default=0, help_text='Total amount spent by customer', max_digits=12)),
                ('notes', models.TextField(blank=True, help_text='Optional notes about this customer', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Customer Contact',
                'verbose_name_plural': 'Customer Contacts',
                'ordering': ['-last_work_date'],
            },
        ),
        migrations.AlterField(
            model_name='work',
            name='customer_name',
            field=models.CharField(blank=True, default='', help_text='Customer name (optional, only needed for notifications)', max_length=255),
        ),
        migrations.AlterField(
            model_name='work',
            name='customer_phone',
            field=models.CharField(blank=True, default='', help_text='Customer phone number for SMS notifications (optional)', max_length=20),
        ),
    ]
