# Generated by Django 5.2.4 on 2025-11-10 10:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0013_customercontact_alter_work_customer_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketingMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Internal name for this message template', max_length=200)),
                ('message', models.TextField(help_text='The promotional message content (max 500 characters)', max_length=500)),
                ('link_url', models.URLField(blank=True, help_text='Optional URL to include in the message', max_length=500, null=True)),
                ('link_text', models.CharField(blank=True, help_text='Text to display for the link (e.g., "Click here")', max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this message template is active and available for use')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('times_used', models.IntegerField(default=0, help_text='Number of times this message has been sent')),
                ('last_used', models.DateTimeField(blank=True, help_text='Date this message was last sent', null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marketing_messages_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Marketing Message',
                'verbose_name_plural': 'Marketing Messages',
                'ordering': ['-created_at'],
            },
        ),
    ]
