# Generated by Django 5.2.4 on 2025-11-10 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0014_marketingmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customercontact',
            name='total_works',
            field=models.IntegerField(default=0, help_text='Total number of works for this customer'),
        ),
    ]
