# Generated by Django 5.2.4 on 2025-12-06 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0016_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='services.material'),
        ),
        migrations.AddField(
            model_name='notification',
            name='procurement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='services.procurement'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('new_work', 'New Work'), ('work_reopened', 'Work Reopened'), ('work_completed', 'Work Completed'), ('low_stock', 'Low Stock Alert'), ('material_request', 'Material Request'), ('procurement_created', 'Procurement Created'), ('procurement_delivered', 'Procurement Delivered'), ('material_pickup', 'Material Pickup')], max_length=30),
        ),
    ]
