# Generated by Django 5.2.4 on 2026-05-14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0018_pendingstockadjustment'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='credit_cleared',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='work',
            name='credit_cleared_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='work',
            name='is_credit',
            field=models.BooleanField(default=False),
        ),
    ]
