# Generated by Django 5.2.4 on 2026-05-25 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0020_daily_sales_report_approval_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingstockadjustment',
            name='adjustment_type',
            field=models.CharField(choices=[('stock_addition', 'Stock Addition'), ('new_material', 'New Material')], default='stock_addition', help_text='Type of adjustment: stock addition to existing material or creation of new material', max_length=20),
        ),
        migrations.AddField(
            model_name='pendingstockadjustment',
            name='material_category',
            field=models.CharField(blank=True, choices=[('paper', 'Paper'), ('ink', 'Ink'), ('binding', 'Binding Supplies'), ('other', 'Other')], help_text='Category for new material (for new_material type)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pendingstockadjustment',
            name='material_name',
            field=models.CharField(blank=True, help_text='Name for new material (for new_material type)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pendingstockadjustment',
            name='material_unit',
            field=models.CharField(blank=True, help_text='Unit of measure for new material (for new_material type)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pendingstockadjustment',
            name='reorder_level',
            field=models.IntegerField(default=0, help_text='Reorder level for new material (for new_material type)'),
        ),
        migrations.AlterField(
            model_name='pendingstockadjustment',
            name='material',
            field=models.ForeignKey(blank=True, help_text='Existing material (for stock_addition type)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pending_adjustments', to='services.material'),
        ),
        migrations.AlterField(
            model_name='pendingstockadjustment',
            name='reason',
            field=models.TextField(help_text='Reason for adding stock or creating material'),
        ),
    ]
