# Generated by Django 5.2.4 on 2026-05-25 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0021_pendingstockadjustment_adjustment_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('new_work', 'New Work'), ('work_reopened', 'Work Reopened'), ('work_completed', 'Work Completed'), ('low_stock', 'Low Stock Alert'), ('material_request', 'Material Request'), ('procurement_created', 'Procurement Created'), ('procurement_delivered', 'Procurement Delivered'), ('material_pickup', 'Material Pickup'), ('stock_adjustment_approved', 'Stock Adjustment Approved'), ('stock_adjustment_rejected', 'Stock Adjustment Rejected')], max_length=30),
        ),
    ]
