# Generated by Django 5.2.4 on 2026-09-04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0022_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcategory',
            name='default_material',
            field=models.ForeignKey(
                blank=True,
                help_text='Material automatically consumed for this category',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='job_categories',
                to='services.material',
            ),
        ),
        migrations.AddField(
            model_name='work',
            name='material',
            field=models.ForeignKey(
                blank=True,
                help_text='Material consumed when this work is created',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='works',
                to='services.material',
            ),
        ),
        migrations.AddField(
            model_name='work',
            name='material_quantity_used',
            field=models.PositiveIntegerField(
                blank=True,
                help_text='Quantity deducted from material stock for this work',
                null=True,
            ),
        ),
    ]
