# Generated by Django 5.2.4 on 2026-09-04 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0024_unified_work_billing_inventory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobcategory',
            name='material',
            field=models.ForeignKey(blank=True, help_text='Material consumed by this category', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories', to='services.material'),
        ),
        migrations.AlterField(
            model_name='jobmaterial',
            name='quantity_used',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='quantity',
            field=models.FloatField(),
        ),
    ]
