import { useEffect, useState } from "react";
import { useNavigate } from "react-router-dom";
import axios from "../utils/axios";
import { formatMoneyGHS } from "../utils/formatMoney";

export default function AdminDashboard() {
  const navigate = useNavigate();
  const [data, setData] = useState(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);

  const load = async () => {
    try {
      setLoading(true);
      const res = await axios.get("/api/services/admin-dashboard/");
      setData(res.data);
      setError(null);
    } catch (err) {
      console.error('Error loading admin dashboard:', err);
      setError("Failed to load admin dashboard data");
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    load();
  }, []);

  if (loading) {
    return (
      <div className="flex items-center justify-center py-8">
        <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-blue-600"></div>
        <span className="ml-2 text-gray-600">Loading admin data...</span>
      </div>
    );
  }

      if (error) {
    return (
      <div className="text-center py-8">
        <h3 className="text-lg font-semibold text-gray-800 mb-2">Error Loading Admin Dashboard</h3>
        <p className="text-gray-600 mb-4">{error}</p>
        <button 
          onClick={load}
          className="px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition-colors"
        >
          Try Again
        </button>
      </div>
    );
  }

  if (!data) {
    return (
      <div className="text-center py-8">
        <h3 className="text-lg font-semibold text-gray-800">No Data Available</h3>
        <p className="text-gray-600">Admin dashboard data is not available at the moment.</p>
      </div>
    );
  }

  return (
    <div className="space-y-6 min-w-0">
      {/* Page title */}
      <div>
        <h2 className="text-2xl font-bold text-gray-800">System Overview</h2>
        <p className="text-gray-600 mt-1">Key metrics and employee performance</p>
      </div>

      {/* Stats cards */}
      <div className="grid grid-cols-12 gap-4">
        <div className="col-span-12 sm:col-span-3 p-4 bg-gradient-to-br from-purple-600 to-purple-700 text-white rounded-lg shadow min-w-0 overflow-hidden">
          <div className="flex flex-col justify-between h-full">
            <div>
              <h3 className="text-sm font-medium opacity-90 truncate">Total Works</h3>
            </div>
            <div>
              <p className="text-xl font-bold mt-2 truncate break-words" title={data.total_works?.toLocaleString()}>
                {data.total_works?.toLocaleString()}
              </p>
            </div>
          </div>
        </div>

        <div className="col-span-12 sm:col-span-6 p-4 bg-gradient-to-br from-green-600 to-green-700 text-white rounded-lg shadow min-w-0 overflow-hidden">
          <div className="flex flex-col justify-between h-full">
            <div>
              <h3 className="text-sm font-medium opacity-90 truncate">Total Revenue</h3>
            </div>
            <div>
              <p className="text-xl font-bold mt-2 truncate break-words" title={`GH₵${parseFloat(data.total_revenue || 0).toLocaleString()}`}>
                {formatMoneyGHS(parseFloat(data.total_revenue || 0))}
              </p>
            </div>
          </div>
        </div>

        <div onClick={() => navigate('/portal/customer-contacts')} className="col-span-12 sm:col-span-3 p-3 bg-gradient-to-br from-blue-600 to-blue-700 text-white rounded-lg shadow cursor-pointer hover:shadow-md transition-all min-w-0 overflow-hidden">
          <div className="flex items-center justify-center h-full">
            <div className="text-center">
              <h3 className="text-sm font-medium truncate">Customer Contacts</h3>
              <p className="text-xs mt-1 opacity-80">Send SMS</p>
            </div>
          </div>
        </div>
      </div>

      {/* Payments by employee */}
      <div className="bg-white rounded-xl shadow-lg border border-gray-100">
        <div className="p-6 border-b border-gray-100">
          <h3 className="text-lg font-semibold text-gray-800">Employee Performance</h3>
          <p className="text-gray-600 text-sm mt-1">Revenue generated by each team member</p>
        </div>
        
        <div className="p-6">
          {data.payments_by_employee && data.payments_by_employee.length > 0 ? (
            <div className="overflow-x-auto">
              <table className="w-full min-w-full">
                <thead className="bg-gray-50">
                  <tr>
                    <th className="text-left p-3 text-sm font-semibold text-gray-700">Employee</th>
                    <th className="text-left p-3 text-sm font-semibold text-gray-700">Transactions</th>
                    <th className="text-left p-3 text-sm font-semibold text-gray-700">Total Revenue</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-gray-100">
                  {data.payments_by_employee.map((emp) => (
                    <tr
                      key={emp.id}
                      className="hover:bg-gray-50 transition-colors"
                    >
                      <td className="p-3">
                        <div className="flex items-center space-x-3">
                          <div className="w-8 h-8 bg-blue-100 rounded-full flex items-center justify-center">
                            <span className="text-blue-600 font-semibold text-sm">
                              {emp.username ? emp.username.charAt(0).toUpperCase() : emp.email.charAt(0).toUpperCase()}
                            </span>
                          </div>
                          <span className="font-medium text-gray-800">@{emp.username || emp.email}</span>
                        </div>
                      </td>
                      <td className="p-3">
                        <span className="inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium bg-blue-100 text-blue-800">
                          {emp.payments_count}
                        </span>
                      </td>
                      <td className="p-3">
                        <span className="font-bold text-green-600" title={`GH₵${parseFloat(emp.payments_total || 0).toLocaleString()}`}>
                          {formatMoneyGHS(parseFloat(emp.payments_total || 0))}
                        </span>
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          ) : (
            <div className="text-center py-8">
              <h4 className="text-lg font-semibold text-gray-800 mb-2">No Performance Data</h4>
              <p className="text-gray-600">Employee payment data will appear here once transactions are processed.</p>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
